import { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { ApiError, classifyError, fieldId, request, type ErrorKind } from "./api";
import { emptyIntentFormValues, formValuesFromIntent, intentStatusLabels, splitIntents, type Intent, type IntentFormValues } from "./intentForm";
import { emptyFormValues, formValuesFromProject, type LinkInput, type Project, type ProjectFormValues } from "./projectForm";
import "./styles.css";

type FieldProps = { id: string; "aria-invalid"?: true; "aria-describedby"?: string };
const summaryId = "form-error-summary";
const fieldProps = (invalid: ReadonlySet<string>, id: string): FieldProps => invalid.has(id) ? { id, "aria-invalid": true, "aria-describedby": summaryId } : { id };

const Shell = ({ children }: { children: ReactNode }) => <><header className="site-header"><Link to="/" className="brand"><span>◒</span> Compass</Link><p>Direction workspace</p></header>{children}</>;
const Loading = () => <div className="state-card" role="status">読み込み中...</div>;
const ErrorState = ({ message }: { message: string }) => <div className="state-card error" role="alert">{message}</div>;

const ProjectListPage = () => {
  const [projects, setProjects] = useState<Project[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { request<{ projects: Project[] }>("/api/projects").then(({ projects }) => setProjects(projects)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "other" ? classified.message : "不明なエラー"); }); }, []);
  return <Shell><main><div className="page-heading"><div><p className="eyebrow">Projects</p><h1>進む理由を、見失わない。</h1></div><Link to="/projects/new" className="button">Projectを作成</Link></div><p className="lede">MissionとVisionを軸に、判断の原則・制約・参照先をひとつの場所にまとめます。</p>
    {error ? <ErrorState message={`Projectの読み込みに失敗しました: ${error}`} /> : projects === null ? <Loading /> : projects.length === 0 ? <div className="state-card"><h2>最初のProjectを作成しましょう</h2><p>この現場が存在する理由から始めます。</p><Link to="/projects/new" className="text-link">作成フォームを開く →</Link></div> : <section className="project-grid" aria-label={`${projects.length}件のProject`}>{projects.map((project) => <Link className="project-card" to={`/projects/${project.id}`} key={project.id}><p className="card-label">Project</p><h2>{project.name}</h2>{project.description && <p>{project.description}</p>}<div className="mission-preview"><span>Mission</span>{project.mission}</div><time>{new Date(project.updatedAt).toLocaleDateString("ja-JP")} 更新</time></Link>)}</section>}
  </main></Shell>;
};

const TextListInput = ({ legend, name, values, setValues, placeholder, invalid }: { legend: string; name: string; values: string[]; setValues: (values: string[]) => void; placeholder: string; invalid: ReadonlySet<string> }) => <fieldset className="repeat-field"><legend>{legend}</legend>{values.map((value, index) => <div className="repeat-row" key={index}><input {...fieldProps(invalid, fieldId(`${name}.${index}`))} aria-label={`${legend} ${index + 1}`} value={value} placeholder={placeholder} onChange={(event) => setValues(values.map((item, i) => i === index ? event.target.value : item))} /><button type="button" className="remove" onClick={() => setValues(values.filter((_, i) => i !== index))}>削除</button></div>)}<button type="button" className="add-row" onClick={() => setValues([...values, ""])}>＋ {legend}を追加</button></fieldset>;

const LinkListInput = ({ legend, name, values, setValues, invalid, withKind = false }: { legend: string; name: string; values: LinkInput[]; setValues: (values: LinkInput[]) => void; invalid: ReadonlySet<string>; withKind?: boolean }) => <fieldset className="repeat-field"><legend>{legend}</legend>{values.map((value, index) => <div className="repeat-row links" key={index}><input {...fieldProps(invalid, fieldId(`${name}.${index}.name`))} aria-label={`${legend} ${index + 1}の名前`} value={value.name} placeholder="名前" onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /><input {...fieldProps(invalid, fieldId(`${name}.${index}.url`))} aria-label={`${legend} ${index + 1}のURL`} type="url" value={value.url} placeholder="https://..." onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, url: event.target.value } : item))} />{withKind && <input {...fieldProps(invalid, fieldId(`${name}.${index}.kind`))} aria-label={`${legend} ${index + 1}の種類`} value={value.kind} placeholder="種類（任意）" onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, kind: event.target.value } : item))} />}<button type="button" className="remove" onClick={() => setValues(values.filter((_, i) => i !== index))}>削除</button></div>)}<button type="button" className="add-row" onClick={() => setValues([...values, { name: "", url: "", kind: "" }])}>＋ {legend}を追加</button></fieldset>;

type FormError = Exclude<ErrorKind, { kind: "not_found" }>;
type ProjectFormProps = { initial: ProjectFormValues; heading: { eyebrow: string; title: string; lede: string }; submitLabel: string; pendingLabel: string; cancelTo: string; save: (values: ProjectFormValues) => Promise<Project> };

const ProjectForm = ({ initial, heading, submitLabel, pendingLabel, cancelTo, save }: ProjectFormProps) => {
  const navigate = useNavigate(); const [name, setName] = useState(initial.name); const [description, setDescription] = useState(initial.description); const [mission, setMission] = useState(initial.mission); const [vision, setVision] = useState(initial.vision); const [principles, setPrinciples] = useState(initial.principles); const [constraints, setConstraints] = useState(initial.constraints); const [repositories, setRepositories] = useState(initial.repositories); const [resources, setResources] = useState(initial.resources); const [error, setError] = useState<FormError | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const errorRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (error) { errorRef.current?.focus(); errorRef.current?.scrollIntoView({ block: "center" }); } }, [error]);
  const invalid: ReadonlySet<string> = new Set(error?.kind === "validation" ? error.issues.flatMap((issue) => issue.fieldId ? [issue.fieldId] : []) : []);
  // 保存に失敗しても入力state（上のuseState）は維持し、そのまま再送信できる。
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setIsSubmitting(true); try { const project = await save({ name, description, mission, vision, principles, constraints, repositories, resources }); navigate(`/projects/${project.id}`); } catch (reason) { const classified = classifyError(reason); setError(classified.kind === "validation" ? classified : { kind: "other", message: classified.kind === "other" ? classified.message : "Projectが見つかりません。削除された可能性があります。" }); } finally { setIsSubmitting(false); } };
  return <Shell><main className="narrow"><Link to={cancelTo} className="back-link">← {cancelTo === "/" ? "Project一覧" : "Project詳細"}</Link><div className="page-heading"><div><p className="eyebrow">{heading.eyebrow}</p><h1>{heading.title}</h1></div></div><p className="lede">{heading.lede}</p>{error && <div className="state-card error" role="alert" id={summaryId} tabIndex={-1} ref={errorRef}>{error.kind === "validation" ? <><p className="error-title">入力内容を確認してください</p><ul>{error.issues.map((issue, index) => <li key={index}>{issue.fieldId ? <a href={`#${issue.fieldId}`}>{issue.label}</a> : issue.label}: {issue.message}</li>)}</ul></> : <><p className="error-title">保存に失敗しました。時間をおいて再試行してください。</p><p>{error.message}</p></>}</div>}<form onSubmit={submit} className="project-form">
    <section className="form-section"><h2>Identity</h2><label>Project名 <span>必須</span><input {...fieldProps(invalid, "field-name")} required aria-required="true" maxLength={100} value={name} onChange={(event) => setName(event.target.value)} /></label><label>説明<textarea {...fieldProps(invalid, "field-description")} maxLength={1000} rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label></section>
    <section className="form-section"><h2>Direction</h2><label>Mission <span>必須</span><small>このProjectが存在する理由</small><textarea {...fieldProps(invalid, "field-mission")} required aria-required="true" maxLength={2000} rows={5} value={mission} onChange={(event) => setMission(event.target.value)} /></label><label>Vision<small>最終的に実現したい状態</small><textarea {...fieldProps(invalid, "field-vision")} maxLength={2000} rows={5} value={vision} onChange={(event) => setVision(event.target.value)} /></label><TextListInput legend="Principles" name="principles" invalid={invalid} values={principles} setValues={setPrinciples} placeholder="迷ったときの判断原則" /><TextListInput legend="Constraints" name="constraints" invalid={invalid} values={constraints} setValues={setConstraints} placeholder="超えてはいけない制約" /></section>
    <section className="form-section"><h2>References</h2><LinkListInput legend="Repositories" name="repositories" invalid={invalid} values={repositories} setValues={setRepositories} /><LinkListInput legend="Resources" name="resources" invalid={invalid} values={resources} setValues={setResources} withKind /></section>
    <div className="form-actions"><Link to={cancelTo} className="secondary-button">キャンセル</Link><button className="button" disabled={isSubmitting}>{isSubmitting ? pendingLabel : submitLabel}</button></div></form></main></Shell>;
};

const jsonInit = (method: string, body: unknown): RequestInit => ({ method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });

const ProjectCreatePage = () => <ProjectForm initial={emptyFormValues} heading={{ eyebrow: "New project", title: "Projectを作成", lede: "必須なのは名前、Missionです。ほかの情報も今ここで整理できます。" }} submitLabel="Projectを作成" pendingLabel="作成中..." cancelTo="/" save={async (values) => (await request<{ project: Project }>("/api/projects", jsonInit("POST", values))).project} />;

const ProjectEditPage = () => {
  const { projectId = "" } = useParams(); const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { request<{ project: Project }>(`/api/projects/${projectId}`).then(({ project }) => setProject(project)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "not_found" ? "Projectが見つかりません。" : `読み込みに失敗しました: ${classified.kind === "other" ? classified.message : "入力内容が不正です"}`); }); }, [projectId]);
  if (error) return <Shell><main className="narrow"><Link to="/" className="back-link">← Project一覧</Link><ErrorState message={error} /></main></Shell>;
  if (!project) return <Shell><main className="narrow"><Loading /></main></Shell>;
  return <ProjectForm initial={formValuesFromProject(project)} heading={{ eyebrow: "Edit project", title: "Projectを編集", lede: "変更した内容は保存するまで反映されません。キャンセルすると保存済みの内容のままです。" }} submitLabel="変更を保存" pendingLabel="保存中..." cancelTo={`/projects/${project.id}`} save={async (values) => (await request<{ project: Project }>(`/api/projects/${project.id}`, jsonInit("PATCH", values))).project} />;
};

const ListSection = ({ title, values }: { title: string; values: string[] }) => <section className="detail-section"><h2>{title}</h2>{values.length ? <ul>{values.map((value, index) => <li key={`${index}-${value}`}>{value}</li>)}</ul> : <p className="unset">未設定</p>}</section>;
const ProjectDetailPage = () => { const { projectId = "" } = useParams(); const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { request<{ project: Project }>(`/api/projects/${projectId}`).then(({ project }) => setProject(project)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "not_found" ? "Projectが見つかりません。" : `読み込みに失敗しました: ${classified.kind === "other" ? classified.message : "入力内容が不正です"}`); }); }, [projectId]); return <Shell><main className="narrow"><Link to="/" className="back-link">← Project一覧</Link>{error ? <ErrorState message={error} /> : !project ? <Loading /> : <><div className="detail-hero"><p className="eyebrow">Project</p><h1>{project.name}</h1>{project.description && <p className="lede">{project.description}</p>}<time>{new Date(project.updatedAt).toLocaleString("ja-JP")} 更新</time><Link to={`/projects/${project.id}/edit`} className="button">Projectを編集</Link></div><section className="direction-panel"><div><p className="section-label">Mission</p><p>{project.mission}</p></div><div><p className="section-label">Vision</p><p>{project.vision ?? <span className="unset">未設定</span>}</p></div></section><IntentSection projectId={project.id} /><div className="detail-columns"><ListSection title="Principles" values={project.principles} /><ListSection title="Constraints" values={project.constraints} /></div><LinkSection title="Repositories" values={project.repositories} /><LinkSection title="Resources" values={project.resources} /></>}</main></Shell>; };
const LinkSection = ({ title, values }: { title: string; values: ({ id: string; name: string; url: string; kind?: string | null })[] }) => <section className="detail-section"><h2>{title}</h2>{values.length ? <div className="link-list">{values.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.id}><span>{item.name}</span><small>{item.kind || item.url}</small></a>)}</div> : <p className="unset">未設定</p>}</section>;

// ---- Intent（Step 2）。Strategist・Research・Outcomeは未実装のため、状態や進行を表示しない。 ----
const loadFailureMessage = (classified: ErrorKind, notFound: string) => classified.kind === "not_found" ? notFound : classified.kind === "validation" ? "入力内容が不正です" : classified.message;
const intentPath = (projectId: string, intentId?: string, suffix = "") => `/projects/${projectId}/intents${intentId ? `/${intentId}` : ""}${suffix}`;
const jsonPost = (body?: unknown): RequestInit => body === undefined ? { method: "POST" } : jsonInit("POST", body);

const IntentFacts = ({ intent }: { intent: Intent }) => <dl className="intent-facts"><dt>実現したい状態</dt><dd>{intent.desiredState}</dd><dt>完了の定義</dt><dd>{intent.completionDefinition ?? <span className="unset">未設定</span>}</dd></dl>;

const IntentSection = ({ projectId }: { projectId: string }) => {
  const [intents, setIntents] = useState<Intent[] | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { request<{ intents: Intent[] }>(`/api/projects/${projectId}/intents`).then(({ intents }) => setIntents(intents)).catch((reason: unknown) => setError(loadFailureMessage(classifyError(reason), "Projectが見つかりません。"))); }, [projectId]);
  const { active, past } = splitIntents(intents ?? []);
  return <section className="detail-section intent-section" aria-labelledby="intent-heading"><h2 id="intent-heading">Intent</h2><p className="section-note">Humanが今実現したい状態です。Missionとは別に、達成や放棄で終わります。</p>
    {error ? <ErrorState message={`Intentの読み込みに失敗しました: ${error}`} /> : intents === null ? <Loading /> : <>
      {active ? <article className="intent-card"><span className="status-badge">{intentStatusLabels.active}</span><h3>{active.title}</h3><IntentFacts intent={active} /><Link to={intentPath(projectId, active.id)} className="secondary-button">詳細・編集</Link></article> : <div className="intent-empty"><p className="unset">Intentは未登録です</p><Link to={intentPath(projectId, "new")} className="button">Intentを登録</Link></div>}
      {past.length > 0 && <details className="past-intents"><summary>過去のIntent（{past.length}件）</summary><ul>{past.map((intent) => <li key={intent.id}><Link to={intentPath(projectId, intent.id)}><span className="status-badge muted">{intentStatusLabels[intent.status]}</span> {intent.title}</Link></li>)}</ul></details>}
    </>}
  </section>;
};

type IntentFormProps = { projectId: string; initial: IntentFormValues; heading: { eyebrow: string; title: string; lede: string }; submitLabel: string; pendingLabel: string; cancelTo: string; save: (values: IntentFormValues) => Promise<Intent> };

const IntentForm = ({ projectId, initial, heading, submitLabel, pendingLabel, cancelTo, save }: IntentFormProps) => {
  const navigate = useNavigate(); const [title, setTitle] = useState(initial.title); const [desiredState, setDesiredState] = useState(initial.desiredState); const [completionDefinition, setCompletionDefinition] = useState(initial.completionDefinition); const [error, setError] = useState<FormError | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const errorRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (error) { errorRef.current?.focus(); errorRef.current?.scrollIntoView({ block: "center" }); } }, [error]);
  const invalid: ReadonlySet<string> = new Set(error?.kind === "validation" ? error.issues.flatMap((issue) => issue.fieldId ? [issue.fieldId] : []) : []);
  // 保存に失敗しても入力state（上のuseState）は維持し、そのまま再送信できる。
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setIsSubmitting(true); try { const intent = await save({ title, desiredState, completionDefinition }); navigate(intentPath(projectId, intent.id)); } catch (reason) { const classified = classifyError(reason); setError(classified.kind === "not_found" ? { kind: "other", message: "ProjectまたはIntentが見つかりません。削除された可能性があります。" } : classified); } finally { setIsSubmitting(false); } };
  return <Shell><main className="narrow"><Link to={cancelTo} className="back-link">← 戻る</Link><div className="page-heading"><div><p className="eyebrow">{heading.eyebrow}</p><h1>{heading.title}</h1></div></div><p className="lede">{heading.lede}</p>
    {error && <div className="state-card error" role="alert" id={summaryId} tabIndex={-1} ref={errorRef}>{error.kind === "validation" ? <><p className="error-title">入力内容を確認してください</p><ul>{error.issues.map((issue, index) => <li key={index}>{issue.fieldId ? <a href={`#${issue.fieldId}`}>{issue.label}</a> : issue.label}: {issue.message}</li>)}</ul></> : error.kind === "conflict" ? <><p className="error-title">この操作は現在のIntentの状態と競合しています。</p><p>{error.message}</p>{error.activeIntentId && <Link to={intentPath(projectId, error.activeIntentId)} className="text-link">Active Intentを開く →</Link>}</> : <><p className="error-title">保存に失敗しました。時間をおいて再試行してください。</p><p>{error.message}</p></>}</div>}
    <form onSubmit={submit} className="project-form"><section className="form-section"><label>タイトル <span>必須</span><small>Intentを一言で表す名前（100文字まで）</small><input {...fieldProps(invalid, "field-title")} required aria-required="true" maxLength={100} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>実現したい状態 <span>必須</span><small>Humanが今実現したい状態。実装手段ではなく、実現後の状態を書きます。</small><textarea {...fieldProps(invalid, "field-desiredState")} required aria-required="true" maxLength={2000} rows={6} value={desiredState} onChange={(event) => setDesiredState(event.target.value)} /></label><label>完了の定義<small>何が示されればこのIntent全体が完了と言えるか（任意）</small><textarea {...fieldProps(invalid, "field-completionDefinition")} maxLength={2000} rows={4} value={completionDefinition} onChange={(event) => setCompletionDefinition(event.target.value)} /></label></section>
    <div className="form-actions"><Link to={cancelTo} className="secondary-button">キャンセル</Link><button className="button" disabled={isSubmitting}>{isSubmitting ? pendingLabel : submitLabel}</button></div></form></main></Shell>;
};

const IntentCreatePage = () => { const { projectId = "" } = useParams(); return <IntentForm projectId={projectId} initial={emptyIntentFormValues} heading={{ eyebrow: "New intent", title: "Intentを登録", lede: "必須なのはタイトルと実現したい状態です。Activeなintentは1つのProjectにつき1件までです。" }} submitLabel="Intentを登録" pendingLabel="登録中..." cancelTo={`/projects/${projectId}`} save={async (values) => (await request<{ intent: Intent }>(`/api/projects/${projectId}/intents`, jsonPost(values))).intent} />; };

/** サーバーのNOT_FOUNDメッセージ（Project/Intentで先頭語が異なる）から、どちらが存在しないかを区別する。 */
const useIntentPage = (projectId: string, intentId: string) => {
  const [state, setState] = useState<{ intent: Intent | null; error: string | null }>({ intent: null, error: null });
  useEffect(() => { request<{ intent: Intent }>(`/api/projects/${projectId}/intents/${intentId}`).then(({ intent }) => setState({ intent, error: null })).catch((reason: unknown) => setState({ intent: null, error: reason instanceof ApiError && reason.status === 404 && reason.message.startsWith("Intent") ? "Intentが見つかりません。" : loadFailureMessage(classifyError(reason), "Projectが見つかりません。") })); }, [projectId, intentId]);
  return { ...state, setIntent: (intent: Intent) => setState({ intent, error: null }) };
};

const IntentEditPage = () => {
  const { projectId = "", intentId = "" } = useParams(); const { intent, error } = useIntentPage(projectId, intentId); const back = intentPath(projectId, intentId);
  if (error) return <Shell><main className="narrow"><Link to={`/projects/${projectId}`} className="back-link">← Project詳細</Link><ErrorState message={error} /></main></Shell>;
  if (!intent) return <Shell><main className="narrow"><Loading /></main></Shell>;
  if (intent.status !== "active") return <Shell><main className="narrow"><Link to={back} className="back-link">← Intent詳細</Link><ErrorState message={`${intentStatusLabels[intent.status]}のIntentは編集できません。`} /></main></Shell>;
  return <IntentForm projectId={projectId} initial={formValuesFromIntent(intent)} heading={{ eyebrow: "Edit intent", title: "Intentを編集", lede: "変更した内容は保存するまで反映されません。キャンセルすると保存済みの内容のままです。" }} submitLabel="変更を保存" pendingLabel="保存中..." cancelTo={back} save={async (values) => (await request<{ intent: Intent }>(`/api/projects/${projectId}/intents/${intentId}`, jsonInit("PATCH", values))).intent} />;
};

const IntentDetailPage = () => {
  const { projectId = "", intentId = "" } = useParams(); const { intent, error, setIntent } = useIntentPage(projectId, intentId);
  const [confirming, setConfirming] = useState(false); const [reason, setReason] = useState(""); const [isAbandoning, setIsAbandoning] = useState(false); const [abandonError, setAbandonError] = useState<string | null>(null);
  const abandon = async (event: FormEvent) => { event.preventDefault(); setAbandonError(null); setIsAbandoning(true); try { setIntent((await request<{ intent: Intent }>(`/api/projects/${projectId}/intents/${intentId}/abandon`, jsonPost({ reason }))).intent); setConfirming(false); } catch (failure) { const classified = classifyError(failure); setAbandonError(classified.kind === "validation" ? classified.issues.map((issue) => `${issue.label}: ${issue.message}`).join(" / ") : classified.kind === "not_found" ? "Intentが見つかりません。" : classified.message); } finally { setIsAbandoning(false); } };
  return <Shell><main className="narrow"><Link to={`/projects/${projectId}`} className="back-link">← Project詳細</Link>{error ? <ErrorState message={error} /> : !intent ? <Loading /> : <>
    <div className="detail-hero"><p className="eyebrow">Intent</p><h1>{intent.title}</h1><p><span className={`status-badge${intent.status === "active" ? "" : " muted"}`}>{intentStatusLabels[intent.status]}</span></p><time>{new Date(intent.updatedAt).toLocaleString("ja-JP")} 更新</time></div>
    <section className="detail-section"><IntentFacts intent={intent} /></section>
    {intent.status === "abandoned" && <section className="detail-section"><h2>放棄</h2><p>{intent.abandonedReason ?? <span className="unset">理由は記録されていません</span>}</p><p className="section-note">放棄したIntentはActiveに戻せません。続ける場合は新しいIntentを登録してください。</p><Link to={intentPath(projectId, "new")} className="secondary-button">新しいIntentを登録</Link></section>}
    {intent.status === "active" && <div className="action-row"><Link to={intentPath(projectId, intent.id, "/edit")} className="button">Intentを編集</Link><button type="button" className="secondary-button danger" aria-expanded={confirming} onClick={() => setConfirming(true)}>Intentを放棄</button></div>}
    {intent.status === "active" && confirming && <form className="abandon-panel" onSubmit={abandon}><h2>このIntentを放棄しますか？</h2><p>放棄すると編集できず、Activeに戻せません。新しいIntentを登録してやり直せます。</p><label>放棄の理由（任意）<textarea autoFocus maxLength={2000} rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{abandonError && <div className="state-card error" role="alert">{abandonError}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => { setConfirming(false); setAbandonError(null); }}>やめる</button><button className="button danger" disabled={isAbandoning}>{isAbandoning ? "放棄中..." : "放棄する"}</button></div></form>}
  </>}</main></Shell>;
};

const App = () => <Routes><Route path="/" element={<ProjectListPage />} /><Route path="/projects/new" element={<ProjectCreatePage />} /><Route path="/projects/:projectId" element={<ProjectDetailPage />} /><Route path="/projects/:projectId/edit" element={<ProjectEditPage />} /><Route path="/projects/:projectId/intents/new" element={<IntentCreatePage />} /><Route path="/projects/:projectId/intents/:intentId" element={<IntentDetailPage />} /><Route path="/projects/:projectId/intents/:intentId/edit" element={<IntentEditPage />} /></Routes>;
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>);
