import { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { classifyError, fieldId, request, type ErrorKind } from "./api";
import { emptyFormValues, formValuesFromProject, type LinkInput, type Project, type ProjectFormValues } from "./projectForm";
import "./styles.css";

type FieldProps = { id: string; "aria-invalid"?: true; "aria-describedby"?: string };
const summaryId = "form-error-summary";
const fieldProps = (invalid: ReadonlySet<string>, id: string): FieldProps => invalid.has(id) ? { id, "aria-invalid": true, "aria-describedby": summaryId } : { id };

const Shell = ({ children }: { children: ReactNode }) => <><header className="site-header"><Link to="/" className="brand"><span>◒</span> Compass</Link><p>Direction workspace</p></header>{children}</>;
const Loading = () => <div className="state-card" role="status">読み込み中...</div>;
const ErrorState = ({ message }: { message: string }) => <div className="state-card error" role="alert">{message}</div>;

const ProjectListPage = () => {
  const [projects, setProjects] = useState<Project[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { request<{ projects: Project[] }>("/api/projects").then(({ projects }) => setProjects(projects)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "other" ? classified.message : "不明なエラー"); }); }, []);
  return <Shell><main><div className="page-heading"><div><p className="eyebrow">Projects</p><h1>進む理由を、見失わない。</h1></div><Link to="/projects/new" className="button">Projectを作成</Link></div><p className="lede">MissionとVisionを軸に、判断の原則・制約・参照先をひとつの場所にまとめます。</p>
    {error ? <ErrorState message={`Projectの読み込みに失敗しました: ${error}`} /> : projects === null ? <Loading /> : projects.length === 0 ? <div className="state-card"><h2>最初のProjectを作成しましょう</h2><p>この現場が存在する理由から始めます。</p><Link to="/projects/new" className="text-link">作成フォームを開く →</Link></div> : <section className="project-grid" aria-label={`${projects.length}件のProject`}>{projects.map((project) => <Link className="project-card" to={`/projects/${project.id}`} key={project.id}><p className="card-label">Project</p><h2>{project.name}</h2>{project.description && <p>{project.description}</p>}<div className="mission-preview"><span>Mission</span>{project.mission}</div><time>{new Date(project.updatedAt).toLocaleDateString("ja-JP")} 更新</time></Link>)}</section>}
  </main></Shell>;
};

const TextListInput = ({ legend, name, values, setValues, placeholder, invalid }: { legend: string; name: string; values: string[]; setValues: (values: string[]) => void; placeholder: string; invalid: ReadonlySet<string> }) => <fieldset className="repeat-field"><legend>{legend}</legend>{values.map((value, index) => <div className="repeat-row" key={index}><input {...fieldProps(invalid, fieldId(`${name}.${index}`))} aria-label={`${legend} ${index + 1}`} value={value} placeholder={placeholder} onChange={(event) => setValues(values.map((item, i) => i === index ? event.target.value : item))} /><button type="button" className="remove" onClick={() => setValues(values.filter((_, i) => i !== index))}>削除</button></div>)}<button type="button" className="add-row" onClick={() => setValues([...values, ""])}>＋ {legend}を追加</button></fieldset>;

const LinkListInput = ({ legend, name, values, setValues, invalid, withKind = false }: { legend: string; name: string; values: LinkInput[]; setValues: (values: LinkInput[]) => void; invalid: ReadonlySet<string>; withKind?: boolean }) => <fieldset className="repeat-field"><legend>{legend}</legend>{values.map((value, index) => <div className="repeat-row links" key={index}><input {...fieldProps(invalid, fieldId(`${name}.${index}.name`))} aria-label={`${legend} ${index + 1}の名前`} value={value.name} placeholder="名前" onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /><input {...fieldProps(invalid, fieldId(`${name}.${index}.url`))} aria-label={`${legend} ${index + 1}のURL`} type="url" value={value.url} placeholder="https://..." onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, url: event.target.value } : item))} />{withKind && <input {...fieldProps(invalid, fieldId(`${name}.${index}.kind`))} aria-label={`${legend} ${index + 1}の種類`} value={value.kind} placeholder="種類（任意）" onChange={(event) => setValues(values.map((item, i) => i === index ? { ...item, kind: event.target.value } : item))} />}<button type="button" className="remove" onClick={() => setValues(values.filter((_, i) => i !== index))}>削除</button></div>)}<button type="button" className="add-row" onClick={() => setValues([...values, { name: "", url: "", kind: "" }])}>＋ {legend}を追加</button></fieldset>;

type FormError = Exclude<ErrorKind, { kind: "not_found" }>;
type ProjectFormProps = { initial: ProjectFormValues; heading: { eyebrow: string; title: string; lede: string }; submitLabel: string; pendingLabel: string; cancelTo: string; save: (values: ProjectFormValues) => Promise<Project> };

const ProjectForm = ({ initial, heading, submitLabel, pendingLabel, cancelTo, save }: ProjectFormProps) => {
  const navigate = useNavigate(); const [name, setName] = useState(initial.name); const [description, setDescription] = useState(initial.description); const [mission, setMission] = useState(initial.mission); const [vision, setVision] = useState(initial.vision); const [principles, setPrinciples] = useState(initial.principles); const [constraints, setConstraints] = useState(initial.constraints); const [repositories, setRepositories] = useState(initial.repositories); const [resources, setResources] = useState(initial.resources); const [error, setError] = useState<FormError | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const errorRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (error) { errorRef.current?.focus(); errorRef.current?.scrollIntoView({ block: "center" }); } }, [error]);
  const invalid: ReadonlySet<string> = new Set(error?.kind === "validation" ? error.issues.flatMap((issue) => issue.fieldId ? [issue.fieldId] : []) : []);
  // 保存に失敗しても入力state（上のuseState）は維持し、そのまま再送信できる。
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setIsSubmitting(true); try { const project = await save({ name, description, mission, vision, principles, constraints, repositories, resources }); navigate(`/projects/${project.id}`); } catch (reason) { const classified = classifyError(reason); setError(classified.kind === "validation" ? classified : { kind: "other", message: classified.kind === "other" ? classified.message : "Projectが見つかりません。削除された可能性があります。" }); } finally { setIsSubmitting(false); } };
  return <Shell><main className="narrow"><Link to={cancelTo} className="back-link">← {cancelTo === "/" ? "Project一覧" : "Project詳細"}</Link><div className="page-heading"><div><p className="eyebrow">{heading.eyebrow}</p><h1>{heading.title}</h1></div></div><p className="lede">{heading.lede}</p>{error && <div className="state-card error" role="alert" id={summaryId} tabIndex={-1} ref={errorRef}>{error.kind === "validation" ? <><p className="error-title">入力内容を確認してください</p><ul>{error.issues.map((issue, index) => <li key={index}>{issue.fieldId ? <a href={`#${issue.fieldId}`}>{issue.label}</a> : issue.label}: {issue.message}</li>)}</ul></> : <><p className="error-title">保存に失敗しました。時間をおいて再試行してください。</p><p>{error.message}</p></>}</div>}<form onSubmit={submit} className="project-form">
    <section className="form-section"><h2>Identity</h2><label>Project名 <span>必須</span><input {...fieldProps(invalid, "field-name")} required aria-required="true" maxLength={100} value={name} onChange={(event) => setName(event.target.value)} /></label><label>説明<textarea {...fieldProps(invalid, "field-description")} maxLength={1000} rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label></section>
    <section className="form-section"><h2>Direction</h2><label>Mission <span>必須</span><small>このProjectが存在する理由</small><textarea {...fieldProps(invalid, "field-mission")} required aria-required="true" maxLength={2000} rows={5} value={mission} onChange={(event) => setMission(event.target.value)} /></label><label>Vision<small>最終的に実現したい状態</small><textarea {...fieldProps(invalid, "field-vision")} maxLength={2000} rows={5} value={vision} onChange={(event) => setVision(event.target.value)} /></label><TextListInput legend="Principles" name="principles" invalid={invalid} values={principles} setValues={setPrinciples} placeholder="迷ったときの判断原則" /><TextListInput legend="Constraints" name="constraints" invalid={invalid} values={constraints} setValues={setConstraints} placeholder="超えてはいけない制約" /></section>
    <section className="form-section"><h2>References</h2><LinkListInput legend="Repositories" name="repositories" invalid={invalid} values={repositories} setValues={setRepositories} /><LinkListInput legend="Resources" name="resources" invalid={invalid} values={resources} setValues={setResources} withKind /></section>
    <div className="form-actions"><Link to={cancelTo} className="secondary-button">キャンセル</Link><button className="button" disabled={isSubmitting}>{isSubmitting ? pendingLabel : submitLabel}</button></div></form></main></Shell>;
};

const jsonInit = (method: string, body: unknown): RequestInit => ({ method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });

const ProjectCreatePage = () => <ProjectForm initial={emptyFormValues} heading={{ eyebrow: "New project", title: "Projectを作成", lede: "必須なのは名前、Missionです。ほかの情報も今ここで整理できます。" }} submitLabel="Projectを作成" pendingLabel="作成中..." cancelTo="/" save={async (values) => (await request<{ project: Project }>("/api/projects", jsonInit("POST", values))).project} />;

const ProjectEditPage = () => {
  const { projectId = "" } = useParams(); const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { request<{ project: Project }>(`/api/projects/${projectId}`).then(({ project }) => setProject(project)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "not_found" ? "Projectが見つかりません。" : `読み込みに失敗しました: ${classified.kind === "other" ? classified.message : "入力内容が不正です"}`); }); }, [projectId]);
  if (error) return <Shell><main className="narrow"><Link to="/" className="back-link">← Project一覧</Link><ErrorState message={error} /></main></Shell>;
  if (!project) return <Shell><main className="narrow"><Loading /></main></Shell>;
  return <ProjectForm initial={formValuesFromProject(project)} heading={{ eyebrow: "Edit project", title: "Projectを編集", lede: "変更した内容は保存するまで反映されません。キャンセルすると保存済みの内容のままです。" }} submitLabel="変更を保存" pendingLabel="保存中..." cancelTo={`/projects/${project.id}`} save={async (values) => (await request<{ project: Project }>(`/api/projects/${project.id}`, jsonInit("PATCH", values))).project} />;
};

const ListSection = ({ title, values }: { title: string; values: string[] }) => <section className="detail-section"><h2>{title}</h2>{values.length ? <ul>{values.map((value, index) => <li key={`${index}-${value}`}>{value}</li>)}</ul> : <p className="unset">未設定</p>}</section>;
const ProjectDetailPage = () => { const { projectId = "" } = useParams(); const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { request<{ project: Project }>(`/api/projects/${projectId}`).then(({ project }) => setProject(project)).catch((reason: unknown) => { const classified = classifyError(reason); setError(classified.kind === "not_found" ? "Projectが見つかりません。" : `読み込みに失敗しました: ${classified.kind === "other" ? classified.message : "入力内容が不正です"}`); }); }, [projectId]); return <Shell><main className="narrow"><Link to="/" className="back-link">← Project一覧</Link>{error ? <ErrorState message={error} /> : !project ? <Loading /> : <><div className="detail-hero"><p className="eyebrow">Project</p><h1>{project.name}</h1>{project.description && <p className="lede">{project.description}</p>}<time>{new Date(project.updatedAt).toLocaleString("ja-JP")} 更新</time><Link to={`/projects/${project.id}/edit`} className="button">Projectを編集</Link></div><section className="direction-panel"><div><p className="section-label">Mission</p><p>{project.mission}</p></div><div><p className="section-label">Vision</p><p>{project.vision ?? <span className="unset">未設定</span>}</p></div></section><div className="detail-columns"><ListSection title="Principles" values={project.principles} /><ListSection title="Constraints" values={project.constraints} /></div><LinkSection title="Repositories" values={project.repositories} /><LinkSection title="Resources" values={project.resources} /></>}</main></Shell>; };
const LinkSection = ({ title, values }: { title: string; values: ({ id: string; name: string; url: string; kind?: string | null })[] }) => <section className="detail-section"><h2>{title}</h2>{values.length ? <div className="link-list">{values.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.id}><span>{item.name}</span><small>{item.kind || item.url}</small></a>)}</div> : <p className="unset">未設定</p>}</section>;

const App = () => <Routes><Route path="/" element={<ProjectListPage />} /><Route path="/projects/new" element={<ProjectCreatePage />} /><Route path="/projects/:projectId" element={<ProjectDetailPage />} /><Route path="/projects/:projectId/edit" element={<ProjectEditPage />} /></Routes>;
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>);
